Upgrade terraform-provider-pagerduty to v2.9.3
pulumi/pulumi-pagerduty pull request #131
Opened 2023-02-01 01:26 UTC by aq17

Fixes #130 
Fixes #129 
Fixes #125 
Fixes #124 
Fixes #123 
Fixes #122 
Fixes #121 
Fixes #120 
Fixes #118 
Fixes #117 
Fixes #112

2023-02-01 01:52 UTC, iwahbe requested changes

2023-02-01 01:52 UTC, iwahbe commented on provider/resources.go
> +			"pagerduty_incident_workflow_trigger": {Tok: makeResource(mainMod, "PagerdutyIncidentWorkflowTrigger")},
Why do these resources have a "Pagerduty" prefix?

```suggestion
			"pagerduty_incident_workflow":         {Tok: makeResource(mainMod, "IncidentWorkflow")},
			"pagerduty_incident_workflow_trigger": {Tok: makeResource(mainMod, "IncidentWorkflowTrigger")},
```

2023-02-01 01:53 UTC, iwahbe commented
It's a lot easier to review these changes when you use the auto-mapper introduced in `3.38.1`.

2023-02-01 02:13 UTC, aq17 commented
> It's a lot easier to review these changes when you use the auto-mapper introduced in `3.38.1`.

👍🏼 I'll refactor to do so.
The sdks are building successfully locally, not quite sure why they are failing here

2023-02-01 03:11 UTC, AaronFriel commented
@aq17 are files left over from the previous commit? Deleting the sdks and rebuilding tends to fix that.

2023-02-01 18:07 UTC, t0yv0 commented
Something still odd with the Go SDK builds.

2023-02-01 19:03 UTC, AaronFriel reviewed
I misspoke earlier, looks like we need to keep these files as tfgen didn't create them.

2023-02-13 19:43 UTC, aq17 commented
Closing in favor of https://github.com/pulumi/pulumi-pagerduty/pull/136.

2023-02-13 19:43 UTC, closed without merging